---
env:
  global:
  - secure: |-
      IzTN2uuR4nsJ8+1IRmLXxn29+MK8PuKYgArbAU/aQPPm1vIUdMv0AYF/rq9N
      YBdJJqfUHwOcGBFuwX1oKp4ykb6VTdYGOOCAN0j3IWtDXMkFM+qSTsLishyw
      wSR11Z5SzTPxMGrY8cOupSH8mckmJvecomcYLctZdYwiP72+rSs=
notifications:
  irc:
    channels:
    - irc.freenode.org#edumips64
    skip_join: true
language: java
python:
- "2.7"
node_js:
- "5"
install: 
- "sudo pip install Sphinx==1.1.3 && gradle getLibs"
- "npm install -g bower gulp && cd src/main/web && npm install && bower install"
script:
- "ant test"
- gulp
jdk:
- oraclejdk8
after_success: ./utils/update-gh-pages.sh
